### ISSUE TITLE
Go doesn't like the keys generated from self-signed

### ISSUE THREAD

**Issue by nkcmr** [indutny/self-signed#2]
Whenever I generate keys from this handy website and put them into Go's `http.ListenAndServeTLS`, it complains about it here: https://github.com/golang/go/blob/7603aa7907fa92336fd9f7702b709e559ee0191b/src/crypto/x509/x509.go#L941

The following program for example:
```go
package main

import (
	"log"
	"net/http"
)

func main() {
	http.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		w.Write([]byte("hi"))
	})
	err := http.ListenAndServeTLS(":8443", "./ss.cert", "./ss.key", http.DefaultServeMux)
	if err != nil {
		log.Fatal("error: ", err)
	}
}
```

will generate the following output:
```
$ go version
go version go1.8 darwin/amd64
$ go run foo.go
2017/02/21 17:15:26 error: x509: RSA key missing NULL parameters
exit status 1
```

I know this tool was made for node.js purposes, but I thought it would be handy to know about this issue.

Thanks for reading!

**Comment by indutny** [comment]
Pushed out a fix, could you please give it a try?

**Comment by nkcmr** [comment]
fixed! thanks for the fast response @indutny.

cheers!

**Comment by indutny** [comment]
No problem!

**Comment by indutny** [comment]
Are you using it at Cloudflare? :wink:

**Comment by terinjokes** [comment]
@indutny Yeah, that cfssl thing is way too complicated.  😜

**Comment by nkcmr** [comment]
@indutny yup. it is pretty nifty for (quickly) generating tiny key pairs for unit tests.

**Comment by indutny** [comment]
Lovely! Let me know if you need any extra buttons on the website :wink:
